# Generated by Django 5.1.7 on 2025-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_content', '0003_sensordata_luminosity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='pH',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
    ]
